const fs = require("fs");
const path = require("path");
const dotenv = require("dotenv");
const { Client } = require("pg");

dotenv.config();

const migrationsDir = path.join(__dirname, "migrations");

const getDatabaseUrl = () => {
  const url = process.env.DATABASE_URL;
  if (!url) {
    throw new Error("DATABASE_URL is required to run migrations");
  }
  return url;
};

const listMigrationFiles = async () => {
  const entries = await fs.promises.readdir(migrationsDir, { withFileTypes: true });
  return entries
    .filter((e) => e.isFile() && e.name.endsWith(".sql"))
    .map((e) => e.name)
    .sort((a, b) => a.localeCompare(b));
};

const ensureMigrationsTable = async (client) => {
  await client.query(`
    create table if not exists schema_migrations (
      id integer generated by default as identity primary key,
      name text not null unique,
      applied_at timestamptz not null default now()
    )
  `);
};

const getAppliedMigrations = async (client) => {
  const result = await client.query("select name from schema_migrations order by name asc");
  return new Set(result.rows.map((r) => r.name));
};

const applyMigration = async (client, name) => {
  const fullPath = path.join(migrationsDir, name);
  const sql = await fs.promises.readFile(fullPath, "utf8");

  await client.query("begin");
  try {
    await client.query(sql);
    await client.query("insert into schema_migrations (name) values ($1)", [name]);
    await client.query("commit");
  } catch (err) {
    await client.query("rollback");
    throw err;
  }
};

const main = async () => {
  const client = new Client({ connectionString: getDatabaseUrl() });
  await client.connect();

  try {
    await ensureMigrationsTable(client);

    const files = await listMigrationFiles();
    const applied = await getAppliedMigrations(client);

    const pending = files.filter((f) => !applied.has(f));
    if (pending.length === 0) {
      console.log("No pending migrations.");
      return;
    }

    for (const name of pending) {
      console.log(`Applying ${name}...`);
      await applyMigration(client, name);
    }

    console.log("Migrations complete.");
  } finally {
    await client.end();
  }
};

main().catch((err) => {
  console.error("Migration failed:", err);
  process.exitCode = 1;
});

