-- database schema snapshot for the server (excluding auth.controller.js)
-- safe to re-run (uses if not exists where possible)

-- note: postgres does not support "create database if not exists" in plain sql.
-- create database ss;

create schema if not exists kss;

-- users
create table if not exists kss.users
(
    id                integer generated by default as identity primary key,
    email             text        not null unique,
    password_hash     text        not null,
    name              text        not null,
    username          text unique,
    bio               text,
    avatar_url        text,
    website_url       text,
    location          text,
    timezone          text,
    phone             text,
    is_active         boolean     not null default true,
    is_private        boolean     not null default false,
    role              text        not null default 'user' check (role in ('user', 'admin')),
    settings          jsonb       not null default '{}'::jsonb,
    email_verified_at timestamptz,
    last_login_at     timestamptz,
    created_at        timestamptz not null default now(),
    updated_at        timestamptz not null default now()
);

create unique index if not exists users_username_key on kss.users (username);

-- shared updated_at trigger function
create or replace function public.set_updated_at()
    returns trigger as
$$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

drop trigger if exists users_set_updated_at on kss.users;
create trigger users_set_updated_at
    before update
    on kss.users
    for each row
execute function public.set_updated_at();

-- relations (friend requests / friendships)
create table if not exists kss.relations
(
    id           integer generated by default as identity primary key,
    user_a       integer     not null references kss.users (id) on delete cascade,
    user_b       integer     not null references kss.users (id) on delete cascade,
    requested_by integer     not null references kss.users (id) on delete cascade,
    status       text        not null check (status in ('pending', 'accepted', 'rejected')),
    created_at   timestamptz not null default now(),
    constraint relations_order check (user_a < user_b),
    constraint relations_pair_unique unique (user_a, user_b),
    constraint relations_not_self check (user_a <> user_b),
    constraint relations_requested_by_in_pair check (requested_by = user_a or requested_by = user_b)
);

create index if not exists relations_lookup_idx on kss.relations (user_a, user_b);
create index if not exists relations_status_idx on kss.relations (status);
create index if not exists relations_requested_by_idx on kss.relations (requested_by);

-- posts
create table if not exists kss.posts
(
    id          integer generated by default as identity primary key,
    author_id   integer     not null references kss.users (id) on delete cascade,
    type        text        not null check (type in ('status', 'link', 'video', 'media')),
    text        text,
    link_url    text,
    video_url   text,
    attachments jsonb       not null default '[]'::jsonb,
    visibility  text        not null default 'public' check (visibility in ('public', 'friends', 'private')),
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now(),
    edited_at   timestamptz,
    deleted_at  timestamptz
);

create index if not exists posts_author_id_idx on kss.posts (author_id);
create index if not exists posts_created_at_idx on kss.posts (created_at desc);
create index if not exists posts_visibility_idx on kss.posts (visibility);

drop trigger if exists posts_set_updated_at on kss.posts;
create trigger posts_set_updated_at
    before update
    on kss.posts
    for each row
execute function public.set_updated_at();

-- subscriptions (user follows)
create table if not exists kss.subscriptions
(
    id             integer generated by default as identity primary key,
    subscriber_id  integer     not null references kss.users (id) on delete cascade,
    target_user_id integer     not null references kss.users (id) on delete cascade,
    created_at     timestamptz not null default now(),
    updated_at     timestamptz not null default now(),
    deleted_at     timestamptz,
    constraint subscriptions_not_self check (subscriber_id <> target_user_id),
    constraint subscriptions_pair_unique unique (subscriber_id, target_user_id)
);

create index if not exists subscriptions_subscriber_active_idx
    on kss.subscriptions (subscriber_id, created_at desc)
    where deleted_at is null;

create index if not exists subscriptions_target_active_idx
    on kss.subscriptions (target_user_id, created_at desc)
    where deleted_at is null;

drop trigger if exists subscriptions_set_updated_at on kss.subscriptions;
create trigger subscriptions_set_updated_at
    before update
    on kss.subscriptions
    for each row
execute function public.set_updated_at();
