-- initial schema for the app (users + relations)

create schema if not exists kss;

-- users
create table if not exists kss.users
(
    id                integer generated by default as identity primary key,
    email             text        not null unique,
    password_hash     text        not null,
    name              text        not null,
    username          text unique,
    bio               text,
    avatar_url        text,
    website_url       text,
    location          text,
    timezone          text,
    phone             text,
    is_active         boolean     not null default true,
    is_private        boolean     not null default false,
    role              text        not null default 'user' check (role in ('user', 'admin')),
    settings          jsonb       not null default '{}'::jsonb,
    email_verified_at timestamptz,
    last_login_at     timestamptz,
    created_at        timestamptz not null default now(),
    updated_at        timestamptz not null default now()
);

create unique index if not exists users_username_key on kss.users (username);

-- shared updated_at trigger function
create or replace function public.set_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

drop trigger if exists users_set_updated_at on kss.users;
create trigger users_set_updated_at
before update on kss.users
for each row
execute function public.set_updated_at();

-- relations (friend requests / friendships)
create table if not exists kss.relations
(
    id           integer generated by default as identity primary key,
    user_a       integer     not null references kss.users (id) on delete cascade,
    user_b       integer     not null references kss.users (id) on delete cascade,
    requested_by integer     not null references kss.users (id) on delete cascade,
    status       text        not null check (status in ('pending', 'accepted', 'rejected')),
    created_at   timestamptz not null default now(),
    constraint relations_order check (user_a < user_b),
    constraint relations_pair_unique unique (user_a, user_b),
    constraint relations_not_self check (user_a <> user_b),
    constraint relations_requested_by_in_pair check (requested_by = user_a or requested_by = user_b)
);

create index if not exists relations_lookup_idx on kss.relations (user_a, user_b);
create index if not exists relations_status_idx on kss.relations (status);
create index if not exists relations_requested_by_idx on kss.relations (requested_by);

