-- posts

create table if not exists kss.posts
(
    id          integer generated by default as identity primary key,
    author_id   integer     not null references kss.users (id) on delete cascade,
    type        text        not null check (type in ('status', 'link', 'video', 'media')),
    text        text,
    link_url    text,
    video_url   text,
    attachments jsonb       not null default '[]'::jsonb,
    visibility  text        not null default 'public' check (visibility in ('public', 'friends', 'private')),
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now(),
    edited_at   timestamptz,
    deleted_at  timestamptz
);

create index if not exists posts_author_id_idx on kss.posts (author_id);
create index if not exists posts_created_at_idx on kss.posts (created_at desc);
create index if not exists posts_visibility_idx on kss.posts (visibility);

drop trigger if exists posts_set_updated_at on kss.posts;
create trigger posts_set_updated_at
before update on kss.posts
for each row
execute function public.set_updated_at();
