-- subscriptions (user follows)

create table if not exists kss.subscriptions
(
    id             integer generated by default as identity primary key,
    subscriber_id  integer     not null references kss.users (id) on delete cascade,
    target_user_id integer     not null references kss.users (id) on delete cascade,
    created_at     timestamptz not null default now(),
    updated_at     timestamptz not null default now(),
    deleted_at     timestamptz,
    constraint subscriptions_not_self check (subscriber_id <> target_user_id),
    constraint subscriptions_pair_unique unique (subscriber_id, target_user_id)
);

create index if not exists subscriptions_subscriber_active_idx
    on kss.subscriptions (subscriber_id, created_at desc)
    where deleted_at is null;

create index if not exists subscriptions_target_active_idx
    on kss.subscriptions (target_user_id, created_at desc)
    where deleted_at is null;

drop trigger if exists subscriptions_set_updated_at on kss.subscriptions;
create trigger subscriptions_set_updated_at
    before update
    on kss.subscriptions
    for each row
execute function public.set_updated_at();

